backend:
  name: git-gateway
  branch: master
local_backend: true
media_folder: /public/img/uploads
public_folder: /img/uploads
collections:
  - name: crossPageData
    label: FAQ and Testimonials
    files:
      - name: faq
        label: FAQs
        file: content/faq.json
        fields:
          - name: application
            label: Application questions
            widget: list
            fields:
              - { name: question, label: Question, widget: string }
              - { name: answer, label: Answer, widget: text }
          - name: accelerator
            label: LCL Accelerator questions
            widget: list
            fields:
              - { name: question, label: Question, widget: string }
              - { name: answer, label: Answer, widget: text }
      - name: testimonials
        label: Testimonials
        file: content/testimonials.json
        fields:
          - name: testimonials
            label: Testimonials
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: class, label: Class, widget: string }
              - { name: message, label: Message, widget: text }
              - name: headshots
                label: Headshots
                widget: list
                fields:
                  - { name: headshot, label: Headshot, widget: image }
  - name: peopleAndCo
    label: People and Companies
    files:
      - name: people
        label: People
        file: content/people.json
        fields:
          - name: speakers
            label: Speakers
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: label, label: Label, widget: string }
              - { name: headshot, label: Headshot, widget: image }
          - name: mentors
            label: Mentors
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: label, label: Label, widget: string }
              - { name: headshot, label: Headshot, widget: image }
          - name: summerAccelerator
            label: Summer Accelerator Team
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: label, label: Label, widget: string }
              - { name: headshot, label: Headshot, widget: image }
          - name: boardMembers
            label: Board Members
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: label, label: Label, widget: string }
              - { name: headshot, label: Headshot, widget: image }
          - name: pastLeadership
            label: Past Leadership
            widget: list
            fields:
              - { name: name, label: Name, widget: string }
              - { name: label, label: Label, widget: string }
              - { name: headshot, label: Headshot, widget: image }
      - name: companies
        label: Companies
        file: content/companies.json
        fields:
          - name: years
            label: Years
            widget: list
            fields:
              - { name: year, label: Year, widget: string }
              - name: companies
                label: Companies
                widget: list
                fields:
                  - { name: name, label: Name, widget: string }
                  - { name: place, label: Place, widget: string, required: false }
                  - { name: descript, label: Description, widget: string, required: false }
                  - { name: logo, label: Logo, widget: image }
  - name: pageContent
    label: Page Content
    files:
      - name: about
        label: About
        file: content/pages/about.json
        fields:
          - name: sections
            label: Page Sections
            widget: list
            fields:
              - { name: heading, label: Heading, widget: string }
              - { name: content, label: Content, widget: markdown }
      - name: team
        label: Team
        file: content/pages/team.json
        fields:
          - { name: text, label: Header text, widget: markdown }
      - name: people
        label: People
        file: content/pages/people.json
        fields:
          - { name: text, label: Header text, widget: markdown }
      - name: cohorts
        label: Cohorts
        file: content/pages/cohorts.json
        fields:
          - name: stats
            label: Header statistics
            widget: list
            fields:
              - { name: label, label: Label, widget: string }
              - { name: value, label: Value, widget: string }
      - name: apply
        label: Apply
        file: content/pages/apply.json
        fields:
          - name: sections
            label: Page Sections
            widget: list
            fields:
              - { name: heading, label: Heading, widget: string }
              - { name: content, label: Content, widget: markdown }
  - name: navbar
    label: Navbar Items
    files:
      - name: navbar
        label: Navbar Items
        file: content/navbar.json
        fields:
          - name: items
            label: Navbar Items
            widget: list
            fields:
              - { name: label, label: Label, widget: string }
              - { name: link, label: Link, widget: string }
  - name: news
    label: News Posts
    folder: "content/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}_{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string"}
      - { label: "Tags", name: "tags", widget: "string"}
      - { label: "Date", name: "date", widget: "datetime"}
      - { label: "Body", name: "body", widget: "markdown"}
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }